### ISSUE TITLE
Django crash when loading the template

### ISSUE THREAD

**Issue by oefterdal** [torchbox/django-libsass#18]
Hi 

When I enable this I get segmentation fault  python manage.py run server

**Comment by gasman** [comment]
Please try the steps listed on https://github.com/torchbox/django-libsass/wiki/Troubleshooting. However, please note that I cannot provide installation support for this package - if you wish to report this as a bug, you'll need to provide the additional info (e.g. installation results on different platforms / versions of Python) to confirm that the issue is with django-libsass and not some other part of the system.

**Comment by oefterdal** [comment]
Hi,


Thank you for your prompt replay. I had no issues when I did the troubleshooting. I will investigate more and post a bug report if I find something. 

Have a nice day.
