### ISSUE TITLE
Lack of information about project structure. 

### ISSUE THREAD

**Issue by aktywnitu** [torchbox/django-libsass#21]
Hi guys,
Thanks for great library.
Unfortunately can't use generated source map - paths to them are really crazy, sometimes buggy I think - for example "/static/all/" instead "static_all".

Please tell me if I need keep my scss files in CAHED/css subdirecotry?
[17/Jun/2016 07:25:39] "GET /static/CACHE/css/bootstrap/_variables.scss HTTP/1.1" 404 1819

css in path?
I have them in COMPRESS_ROOT of course. So, maby I need create symbolic link? Can't more easier? Please explain me and others how it works.

**Comment by gasman** [comment]
Hi @aktywnitu,
There's no specific documentation for django-libsass about this, because we follow the standard approach used by Django and django-compressor. See https://docs.djangoproject.com/en/1.9/intro/tutorial06/, https://docs.djangoproject.com/en/1.9/howto/static-files/deployment/, http://django-compressor.readthedocs.io/en/latest/usage/.

Generally, the best practice is to create a 'static' folder inside one of your apps, and put the static files there - for example, if you have a 'core' app inside your project, you'd put the scss files inside `/core/static/core/scss/`, and refer to them inside your templates as `/static/core/scss/foo.scss`. You should never need to put any files into `/static/CACHE` - that location is used internally by django-compressor.

If you believe the source map paths are broken, then please open a new ticket giving full details of the file paths used by your project, and the expected vs actual behaviour.
