### ISSUE TITLE
LibSass Deprecation

### ISSUE THREAD

**Issue by thismatters** [torchbox/django-libsass#45]
I just learned that [libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated), and I was wondering if this package is going to migrate to another alternative?

**Comment by gasman** [comment]
Thanks, wasn't aware of that!
We switched to node-based front-end tooling for our projects a long time back, and haven't actively used django-libsass since then - if libsass is deprecated now, then it makes sense to consider django-libsass deprecated too. Anyone who wants to fork this code into django-dartsass (or whatever) is welcome to, of course...

**Comment by jmoppel** [comment]
I did a bit more reading about this and it appears that libsass "is mostly dead. Mostly dead is slightly alive."  :smile:  As of 3/27/22, the most recent commit to the [libsass repo](https://github.com/sass/libsass) was in Dec. 2021 and the latest release was May 2021.

> What does “deprecated” mean?
> 
> We’re choosing to use the term “deprecated” because it carries a lot of weight in the programming community, and provides a strong signal that users should start planning to move away from LibSass. However, it doesn’t mean that the project is entirely dead. Michael Mifsud, the lead maintainer of LibSass and Node Sass, has affirmed that he plans to continue maintenance on the same level as the past few years. This means that although there will be no more features added (and as such LibSass will slowly drift further and further out of compatibility with the latest CSS and Sass syntax), there will continue to be maintenance releases indefinitely.
